### ISSUE TITLE
InGameDefEditor conflicts with Dubs Mint Menus

### ISSUE THREAD

**Issue by thakyZ** [KiameV/rimworld-ingamedefeditor#1]
Tested using only `Core`, `HugsLib 6.1.1`, `Mod Manager 1.15.748`, `Dubs Mint Menus 1.0.0` and `In-Game Definition Editor 1.0.0.5` in that order.   

So basically what happens is that the icons in Dubs Mint Menus disappear while this mod is loaded. I have tried to see if it works while this mod is loaded before and it doesn't seem to work at all either way.

Here are the logs:   
https://gist.github.com/HugsLibRecordKeeper/76e1acd57f19fd0f7c4892ac839a9cf6   

Here are some images what happens when both mods are loaded (before/after):
![image](https://user-images.githubusercontent.com/950594/48857678-53a04d00-ed6e-11e8-98c3-8d44535ab320.png)
![image](https://user-images.githubusercontent.com/950594/48857685-569b3d80-ed6e-11e8-836e-69541d16dcba.png)

**Comment by KiameV** [comment]
Should be resolved with last update. Reopen if this is not the case.
